name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew build

      - name: Send JAR to Discord
#        env:
#          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          FILE_PATH=$(find build/libs -name "*.jar" | head -n 1)
          echo "Sending file: $FILE_PATH"
          curl -X POST "https://discord.com/api/webhooks/1378255132654964817/y_Qv-FizHRaV4bTkD3V3Gr7jnQ-iowj84UTCJU2Sp6keh5Iz3VpF7iX8XWR67xc4xn6B" \
            -F "file=@$FILE_PATH" \
            -F "payload_json=$(jq -nc \
              --arg msg "✅ Build successful from commit [$SHORT_SHA](https://github.com/${{ github.repository }}/commit/${{ github.sha }}): $COMMIT_MSG" \
              --arg username "Github" \
              --arg avatar "https://cdn-icons-png.flaticon.com/512/25/25231.png" \
              '{content: $msg, username: $username, avatar_url: $avatar}')'